### ISSUE TITLE
User story: Migrate to new Django version

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/StackPortfolio#191]
### If applicable, add a related Epic.

Epic: 

### User Story

As a developer, I want to migrate our platform to the latest Django version to take advantage of improved features and security patches, ensuring the platform remains modern and secure.

### Acceptance Criteria

- The platform is successfully migrated to the latest Django version.
- All existing functionality is tested and confirmed to work as expected post-migration.
- Any deprecated features are replaced with their updated counterparts.

### Please ensure you've completed these tasks before marking the issue as done.

- [x] Reviewed the user story for clarity and completeness.
- [x] Identified and linked related issues or epics.
- [ ] Updated the issue with any relevant notes or feedback (to date).

### Please add any further tasks that need to be completed before the issue can be marked as done.

- [ ] Assess the changes and deprecations in the new Django version.
- [ ] Update the codebase to accommodate the new version requirements.
- [ ] Thoroughly test the updated platform to ensure stability and performance.

**Comment by stephendawsondev** [comment]
We want to migrate Django to the latest version that will receive long-term support (LTS).

**Comment by KTC96** [comment]
![Image](https://github.com/stephendawsondev/StackPortfolio/assets/121882522/9888f7fe-06ff-4b45-a4b8-49e6a1972dd4)

**Comment by stephendawsondev** [comment]
> 
> 
> ![Image](https://github.com/stephendawsondev/StackPortfolio/assets/121882522/9888f7fe-06ff-4b45-a4b8-49e6a1972dd4)
> 
> 

I found a good medium article: https://medium.com/django-unleashed/upgrade-django32-to-django42-d581d272540e

It might be a case of doing a bit of searching in the code. 

At the end, they mention there is a package called `django-upgrade` that may be worth looking into!
